### ISSUE TITLE
Unable to copy settings of data element and rule from one property to another.

### ISSUE THREAD

**Issue by sharmaabhilashn** [pitchmuc/launchpy#15]
Hi @pitchmuc,

I would like to thankyou for your effort building and managing this module. This is super helpful.

I am looking to copy settings of data element and rule from one property to another. 
The Synchronizer class is not useful as the previous versions will be overridden.

I am using Translator class instead. However, when I run the attached code, I don't see any errors. But the data element is not getting copied.

Can you please let me know if I am missing something here? 
Also, is there a functionality to copy settings of an extension from one Property to another within the same Organization?

Thanks,
Abhi.

[Copy Data Element Adobe Launch API.txt](https://github.com/pitchmuc/launchpy/files/10132853/Copy.Data.Element.Adobe.Launch.API.txt)

**Comment by sharmaabhilashn** [comment]
Thanks for your quick reply @pitchmuc !

I was under the impression that Synchronizer will overwrite the rule/data element without leaving any traces/previous versions.
I will check the Synchronizer class and get back. 

I manage 100+ properties in Launch, if a small change in one extension is required to be published across 100 + properties , it would take a lot of manual effort. Hence trying to automate things.

**Comment by pitchmuc** [comment]
Looking quickly at the code, it seems that you do not copy the setting when you create one Data Element. 
But it looks like you are trying to re-create the Synchronizer with some (command lines) inputs, there are a lot of things to consider if you want to do that. Many edge case scenarios to consider, especially for rules. 
I would definitely try to use the Synchronizer. 
If not 2 options: 

- You try to reverse engineer the Synchronizer to do it your way. You have a good start there. 
- You ask help from Adobe consulting so I can actually get paid to use/develop my wrapper :D 

I would try to debug by printing some data points during creation of data elements and rules.

**Comment by sharmaabhilashn** [comment]
@pitchmuc , Thanks for your inputs. I tried Synchronizer class and I was able to copy Data Elements and Rules without any issues. 
I would definitely look into your suggestions in the meantime. 
Appreciate your help on this!
